### ISSUE TITLE
Item Category editor updates wrong groups

### ISSUE THREAD

**Issue by BlackHat91** [Packer/H3VR-Supply-Raid#1]
When using groups in an item category, if you update an existing group's entries it often saves the updated entry in the previous group that was opened. I have not been able to reliably get it to save an updated entry in the correct group immediately, but if you have 3 or more groups you can juggle the entries into the right groups.

**Comment by Packer** [comment]
Cannot replicate this issue, can you explain how to reproduce this problem?
