### ISSUE TITLE
Request: Save options between sessions

### ISSUE THREAD

**Issue by Audixas** [Packer/H3VR-Supply-Raid#10]
It would be really nice if we could save our supply raid settings between sessions. Especially when playing Safehouse characters, you end up jumping in and out of supply raids pretty often and setting them everytime gets annoying.

**Comment by DesiQuintans** [comment]
Relatedly, I saw that the character CPSR file had things like "death mode" and "death count" so I thought that I'd be able to set preferred settings for allowed deaths with my character, but it seems to be ignored.

**Comment by Packer** [comment]
Profile Saving is now implemented and available in 1.1.2 beta.
