### ISSUE TITLE
Revolvers/internal mag shotguns spawn unwanted ammo in Limited Ammo mode

### ISSUE THREAD

**Issue by DesiQuintans** [Packer/H3VR-Supply-Raid#11]
I was trying to make a limited ammo character, so I put revolvers (e.g. Python) and shotguns (e.g. M1014) into the loot category but with ammo count set to 0 for both spawnlock and limited ammo modes, and with no ammo spawned with the guns themselves. 

I found that if the SR run starts with Spawnlock Enabled, then my settings are respected: the gun spawns by itself. However, if Limited Ammo is enabled then the gun will *always* spawn with extra ammo. In the case of shotguns this results in a stream of about 10 shells falling with the gun. In the case of revolvers with speedloaders, it spawns like 10 speedloaders. 

I don't know if this is a SR bug or a H3 thing, so let me know if this is an H3 bug and I'll report it elsewhere.

**Comment by Packer** [comment]
The ammo choices for each Item Category has been reworked with individual ammo being set now works.
