### ISSUE TITLE
Please expose maxPatrolSize as a variable

### ISSUE THREAD

**Issue by DesiQuintans** [Packer/H3VR-Supply-Raid#12]
From looking at your code, it looks like the maximum size of Patrol squads is calculated with:

```
minPatrolSize + Random.Range(0, Mathf.CeilToInt((float) (enemyCount / 3)
```

It would be great if you made this settable in the `.sfsr` faction file. This would give better control over the number of separate patrol squads at each level.

**Comment by Packer** [comment]
I've added it to my list of things to check for next update.

**Comment by Packer** [comment]
`maxPatrolSize` has been Added to FactionLevel but will default back to the old method if 0 or less.
