### ISSUE TITLE
Misc sosig list for mods (or make sosigs public)

### ISSUE THREAD

**Issue by Wilnath** [Packer/H3VR-Supply-Raid#16]
I'm working on a mod that ends up spawning sosigs on its own, but am still interested in hooking these sosigs up to be managed by SR so they can drop items and be cleared on death.

Currently, I don't see any ways to hook these sosigs up except for `SR_Manager.defenderSosigs` being public, but adding sosigs there has gameplay ramifications.

Adding these spawned sausages directly into `SR_Manager.sosigs` with a publicized assembly worked without any hitches for me, and it would be neat if it was public for this kind of usecase

**Comment by Packer** [comment]
Added `AddCustomSosig` with the ability to choose if they are a defender or just added to the list for level clearing. You can access via `SR_Manager.instance.AddCustomSosig(YourSosig);`. Note though this does not update the sosigs sight automatically (System used for Day/Night, this value can be accessed via `SR_Manager.instance.sosigSightMultiplier`, its a simple multiplier that multiplies the sosigs `stateSightRangeMults` if you want your sosigs to have reduced night vision. e.g. `stateSightRangeMults * sosigSightMultiplier`.
```
        public void AddCustomSosig(Sosig sosig, bool isDefender = false)
        {
            sosigs.Add(sosig);

            if (isDefender)
                defenderSosigs.Add(sosig);
        }
```

**Comment by Wilnath** [comment]
Big thanks for this!
