### ISSUE TITLE
Request: Item Categories assigned to shop do not appear if no items possible/"empty"

### ISSUE THREAD

**Issue by BlackHat91** [Packer/H3VR-Supply-Raid#5]
Item Categories correctly read modded items and if the item is not found, it simply doesn't spawn. If a group only has that item, it just doesn't ever select that group. Which is perfect behavior.

However, if all groups cannot spawn due to the items not found, the shop will produce a pencil. While entertaining, it would be better to have that category just not appear in the shop.

Perhaps when the character is loaded, it would be possible to scan item categories assigned to the shop for groups to see if any listed groups can spawn any item. If tags are disabled for that item category and no item group can spawn any item, that category gets removed from the shop?

**Comment by Packer** [comment]
Added additional checks when populating the buy menu to not generate buttons if they are both empty of group objects AND loot table.
