### ISSUE TITLE
Cannot purchase .38 Special speedloader

### ISSUE THREAD

**Issue by DesiQuintans** [Packer/H3VR-Supply-Raid#8]
# Summary

I cannot buy a .38 Special speedloader from either the Magazine Panel or the Ammo Panel in Supply Raid v1.1.0.

# Steps to reproduce

1. Start a SR game using Picatinny Pierre, enable the Item Spawner, leave all other settings as default.
2. Use the Item Spawner to spawn a Rhino 20 and a Detective Special 38.
3. In the game, place the Rhino 20 on the Ammo Panel and buy a speedloader. A speedloader will appear.
4. Now remove the Rhino and place the Detective Special 38 on the Ammo Panel and buy a speedloader. No speedloader appears.
5. Also note that for both revolvers, even though the Magazine Panel shows a tick mark for "Purchase New Mag", no speedloader can be purchased for either gun here.

**Comment by Packer** [comment]
I'll investigate when I do more panel updates in the near future, its likely to do with the tagging of items on the weapon. Sometimes Anton has forgotten to tag things completely or incorrectly causing the weapon to have no 'ammo' for it. Alternatively I will be looking at improving how this data is interpreted when looking for valid ammo to spawn.

**Comment by DesiQuintans** [comment]
This does seem to be related to other problems that H3 has with the .38 speedloaders in general. For example, I found that I couldn't reload the speedloader with loose .38 cartridges.

**Comment by Packer** [comment]
After looking closer Anton forgot to include the speedloader in the meta data for the weapon, I have however reworked it to better handle all speed loaders.
