### ISSUE TITLE
What is "Custom Mod Cost"?

### ISSUE THREAD

**Issue by DesiQuintans** [Packer/H3VR-Supply-Raid#9]
It is called `modCost` in the character's .CPSR file and `Custom Mod Cost` in the Supply Raid Editor, but it is not documented even in the decompiled SupplyRaid.dll. I tried setting it to an obvious number but never saw it show up on any panels. What does this do?

**Comment by Packer** [comment]
This is not used for anything, it was a "just in case" people modded Supply Raid and wanted some preexisting value they could hook into for cost of their modded items.
